### ISSUE TITLE
Hi James! Gilberto from Plaid here

### ISSUE THREAD

**Issue by ghernandez-plaid** [jcoliz/PlaidQuickstartBlazor#2]
Hi @jcoliz! I hope all is well. My name is Gilberto and I’m on the Developer Relations team at Plaid. I couldn't quite find a good way of getting in contact, so here I am on GitHub! Thank you for porting over the Plaid Quickstart to .NET! Our team is interested in expanding our Plaid community and we’re conducting a bit of research to learn more about how devs engage with us. 

I was wondering if you'd be interested in participating in a 30 minute research session with me and a member of our research team? You would be compensated with a gift card for your time. If you’re interested, let me know and I can send over the Calendly invite so we can schedule some time (we could switch to email, Twitter DM, etc., for communication). Thanks!

**Comment by jcoliz** [comment]
@ghernandez-plaid Hi, Gilberto, thanks for reaching out! I'm happy to help any way I can. For this, you can reach my on my developer email at jcoliz@outlook.com. I'm nominally on twitter @j_coliz, but email definitely preferred. Looking forward to meeting you!

**Comment by ghernandez-plaid** [comment]
Reached out – thanks James! Looking forward to it.
