### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by MuhammadMuzammil67** [jcoliz/PlaidQuickstartBlazor#60]
How it takes secret and client_id from the scret.yaml file? Even there is no reference is showing up.

**Comment by jcoliz** [comment]
`secrets.yaml` is picked up by the main server program in [Server/Program.cs Line 9](https://github.com/jcoliz/PlaidQuickstartBlazor/blob/557d9ff393b50f70a5e87a584d10151c6c99b196/Server/Program.cs#L9):

```c#
// You can put your plaid secrets here. But really you can put them
// ANYWHERE in the .NET configuration system
builder.Configuration.AddYamlFile("secrets.yaml",optional:true);
```

Perhaps you've misspelled it?

**Comment by MuhammadMuzammil67** [comment]
why it is not listening on port 7267?

**Comment by jcoliz** [comment]
It would be helpful if you could post a lot more detail. Please describe what you're doing, and paste here the output you're seeing.

**Comment by MuhammadMuzammil67** [comment]
### Step 1: Link Token
I am at the first step of plaid API to get LinkToken. But ActionMethod crashes due to object property of PlaidClient that is "**CountryCode**" is null and hence "**Object Reference Null Exception**" occurs.  See Attached Screenshot, as it is Action Method of Generating LinkToken.
![Screenshot (76)](https://user-images.githubusercontent.com/38048415/209622830-7aa3e25a-92e2-427d-be6a-d6530eb98939.png)

### **Now see below the Error of Null Reference**
 
![Screenshot (75)](https://user-images.githubusercontent.com/38048415/209623041-99d03b65-65d8-4afc-b9d0-7985d6771976.png)


### Below is the model class of Plaid Client
![Screenshot (77)](https://user-images.githubusercontent.com/38048415/209623128-ee490ca1-f54e-4a05-badf-459a76a9df0f.png)

**Comment by viceroypenguin** [comment]
Based on these screenshots, you are creating a new `CountryCodeClass` from scratch and attempting to use the default values. In this case, the `country.CountryCode` value will be `null`, which means that you will be attempting call `.Split()` on a `null` value, which is why you are getting an NRE. You should read the code of this project better to understand how these values are collected from configuration.

**Comment by MuhammadMuzammil67** [comment]
> Based on these screenshots, you are creating a new `CountryCodeClass` from scratch and attempting to use the default values. In this case, the `country.CountryCode` value will be `null`, which means that you will be attempting call `.Split()` on a `null` value, which is why you are getting an NRE. You should read the code of this project better to understand how these values are collected from configuration.

Alright,
Last but not the least, when I run PlaidQuickstartBlazor.FrontEnd , it gives error "The "**GenerateStaticWebAsssetsPropsFile" task failed unexpectedly**" See the Screenshot below. 
![1st errror](https://user-images.githubusercontent.com/38048415/209790286-014550a1-3ede-4c4d-9ef4-1675f0ea6efe.png)

And if I avoid this error then it give error "**Web server failed to listen on port 7267**". See the Screenshot below.
![2nd eror](https://user-images.githubusercontent.com/38048415/209790305-b9960965-ba6a-4463-8f08-2d431a2b9395.png)

**Comment by MuhammadMuzammil67** [comment]
@viceroypenguin  ???
@jcoliz  ...???

**Comment by viceroypenguin** [comment]
I cannot reproduce, so it's likely an issue on your machine. I'm afraid I can't offer any more help on how to get your machine working right with Blazor. 

If you expand the error message, you may see additional information that will help you search the internet for a solution.

Also recommend you ensure you ahve the latest version of VS (17.4.3), and repair the installation if possible.

**Comment by jcoliz** [comment]
@MuhammadMuzammil67 Are you making changes to the code? First thing is to get the quickstart running with no changes. Are you able to do that?

**Comment by jcoliz** [comment]
No response in 1 month, closing.
