### ISSUE TITLE
Bump Going.Plaid to 5.0.0

### ISSUE THREAD

**Issue by jcoliz** [jcoliz/PlaidQuickstartBlazor#78]
Going.Plaid has breaking changes. Will need to be updated manually.

https://github.com/viceroypenguin/Going.Plaid/releases/tag/v5.0.0

Dependabot #77 just complains about PlaidError ambiguous references.

```
 Error: /home/runner/work/PlaidQuickstartBlazor/PlaidQuickstartBlazor/Server/Controllers/FetchController.cs(37,34): error CS0104: 'PlaidError' is an ambiguous reference between 'Going.Plaid.Entity.PlaidError' and 'PlaidQuickstartBlazor.Shared.PlaidError' [/home/runner/work/PlaidQuickstartBlazor/PlaidQuickstartBlazor/Server/PlaidQuickstartBlazor.Server.csproj]
```

**Comment by viceroypenguin** [comment]
Apologies! I moved `PlaidError` to fit other `Entity` types (previously it was squirreled away in `.Error`.

**Comment by jcoliz** [comment]
@viceroypenguin No worries! The  release notes were clear. I just had to figure out how to handle the changes here.
